questzhuhai/leave/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.views.generic import ListView
from leave.models import LeaveRequest

from django.contrib.admin.sites import AdminSite
from leave.admin import LeaveRequestAdmin
from leave.models import LeaveRequest
leaverequest_admin = LeaveRequestAdmin(LeaveRequest, AdminSite())

from maitenance.views import admin_require

urlpatterns = patterns('',
	url(r'^leaverequest/new/$', "leave.views.leave_request"),
	url(r'^leaverequest/edit/(?P<id>\d+)/$', "leave.views.leave_request", {'edit': True}, name='leave_request_edit'),
	url(r'^leaverequest/approve/(?P<id>\d+)/$', "leave.views.leave_request_approve", name='leave_request_approve'),
	url(r'^leaverequest/reject/(?P<id>\d+)/$', "leave.views.leave_request_reject", name='leave_request_reject'),
	url(r'^leaverequest/archive/(?P<id>\d+)/$', "leave.views.leave_request_archive", name='leave_request_archive'),
	url(r'^leaverequest/cancel/(?P<id>\d+)/$', "leave.views.leave_request_cancel", name='leave_request_cancel'),
	#url(r'^leaverequests/$', "leave.views.leave_request_by_admin"),
	url(r'^leaverequests/$', admin_require(leaverequest_admin.changelist_view)),
	url(r'^leaverequests/my/$', "leave.views.leave_request_by_emp"),
	url(r'^leaverequests/todo/$', "leave.views.leave_request_by_approver"),
	url(r'^leaverequests/(?P<id>\d+)/$', "leave.views.leave_request_view"),
	url(r'^checkrequest$', "leave.views.check_period"),
)

questzhuhai/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.views.generic.simple import direct_to_template

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    url(r'^eleave/admin/', include(admin.site.urls)),
    url(r'^eleave/main/', include('maitenance.urls')),
    url(r'^eleave/leave/', include('leave.urls')),
	url(r'^eleave/$', "leave.views.leave_request"),
	url(r'^$', "leave.views.leave_request"),
)

import settings
if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.STATIC_ROOT,
        }),
   )

questzhuhai/leave/models.py
from django.db import models
import leave.processe.status as status
from maitenance.models import Employee

class LeaveType(models.Model):
	name = models.CharField(max_length=128, unique=True)
	notifyadmin = models.BooleanField(default = False)
	max_days = models.IntegerField(default=0, blank=True, null=True)
	build_in = models.BooleanField(default = False)
	
	def __unicode__(self):
		return self.name
	
class LeaveRequestManager(models.Manager):
	def by_employee(self, emp):
		return self.filter(employee=emp).order_by('-create_date')
		
	def by_approver(self, emp):
		s = emp.domain_id.replace(r'\\', r'\\\\')
		return self.filter(employee__approvers__icontains=s).order_by('-create_date')

class LeaveRequest(models.Model):
	employee = models.ForeignKey(Employee)
	status = models.CharField(max_length=50, default=status.INITIAL)
	leave_type = models.ForeignKey(LeaveType)
	days = models.FloatField(default=0)
	create_date = models.DateTimeField(auto_now_add=True)
	comments = models.CharField(max_length=500, blank=True, null=True)
	objects = LeaveRequestManager()
	
	def __unicode__(self):
		return '%s-%s-%s' % (self.employee.display_name, self.leave_type.name, self.status)
		
	def get_absolute_url(self):
		return '/eleave/leave/leaverequests/%i/' % self.id
	
	def manager_shortcut_actions(self):
		actions = []
		if self.status in (status.PENDINGMANAGER):#, status.WAITINGADMINCONFIRM):
			actions.append(('Approve', '/eleave/leave/leaverequest/approve/%i/' % self.id))
			#('Reject', '/eleave/leave/leaverequest/reject/%i/' % self.id),
		return actions
	
	def started(self):
		periods = self.period_set.all()
		if len(periods) > 0:
			for period in periods:
				if period.have_started():
					return True
		return False
	
	def is_approved(self):
		return self.status in (status.PENDINGADMIN, status.ARCHIVED)
		
	def delay_days(self):
		from datetime import datetime
		return (datetime.now() - self.create_date).days
	
class Period(models.Model):
	leave_request = models.ForeignKey(LeaveRequest)
	start = models.DateTimeField()
	end = models.DateTimeField()
	
	def __unicode__(self):
		return '%s  ~  %s' % (self.start.strftime('%Y-%m-%d %p'), self.end.strftime('%Y-%m-%d %p'))
			
	def have_started(self):
		import datetime
		return datetime.datetime.now() > self.start
	
class LeaveRequestProcesses(models.Model):
	leave_request = models.ForeignKey(LeaveRequest)
	who = models.CharField(max_length=30)
	do = models.CharField(max_length=30)
	at = models.DateTimeField(auto_now=True)
	reason = models.TextField(blank=True, null=True)

questzhuhai/maitenance/models.py
from django.db import models
import datetime
from leave import processe

class Admin(models.Model):
	sid = models.CharField(max_length=512, editable=False, unique=True)
	name = models.CharField(max_length=50)
	
	def __unicode__(self):
		return self.name
	
class MaintenanceLog(models.Model):
	when = models.DateTimeField(auto_now=True)
	who = models.CharField(max_length=50)
	operation = models.CharField(max_length=512)
	
	
class Department(models.Model):
	name = models.CharField(max_length=512, unique=True)
	supervisor = models.CharField(max_length=256, blank=True)
	
	def __unicode__(self):
		return self.name

class Team(models.Model):
	department = models.ForeignKey(Department)
	name = models.CharField(max_length=512, unique=True)
	leader = models.CharField(max_length=50, blank=True)
	
	def __unicode__(self):
		return self.name

class Employee(models.Model):
	sid = models.CharField(max_length=512, editable=False, unique=True)
	domain_id = models.CharField(max_length=50, help_text="Employee's domain id (prod\\awu1)")
	display_name = models.CharField(max_length=128)
	chinese_name = models.CharField(max_length=20, blank=True)
	title = models.CharField(max_length=256)
	email = models.EmailField(max_length=75)
	department = models.ForeignKey(Department, related_name="employees", blank=True, null=True, on_delete=models.SET_NULL)
	team = models.ForeignKey(Team, related_name="team_members",  blank=True, null=True, on_delete=models.SET_NULL, help_text="All teams include in the department which you selected above.")
	join_date = models.DateField(help_text='The date when the employee joined Quest')
	start_fiscal_date = models.DateField(help_text="The start date that used for calculating employee's annual leave for the current year. For example, employee A joined quest on 22/04/2011, his/her StartFiscalDate of 2011 is 22/04/2011; Employee B joined quest on 15/12/2010, his/her StartFiscalDate of 2011 is 01/01/2011.")
	balanced_forward = models.FloatField(default=0, help_text='Days of annual leave that the employee remains from last year (should be less than 5 days and will be cleared at the middle of the calendar year).')
	al_entitlement = models.FloatField(verbose_name=r'A/L', help_text='Days that the employee could have annual leave for each calendar year. ')
	sl_entitlement = models.FloatField(verbose_name=r'S/L', help_text='Days that the employee could have sick leave for each calendar year. ')
	approvers = models.CharField(max_length=256,
		help_text="The persons who can approve/reject the employee's leave requests (prod\\rgong;prod\\awu1;).\n\
			Use ; to separate and end with ;")
	cc_to = models.CharField(max_length=512, blank=True, null=True,
		help_text='Use semicolon to separate all the carbon copy Employees.\n\
			Use ; to separate and end with ;')
	is_administrative_staff = models.BooleanField(verbose_name="Admin", default = False, help_text='Whether the employee is an administrative stuff.')
	is_active =  models.BooleanField(default = True, help_text='Whether the employee still work for quest or not.')
	last_login_date = models.DateTimeField(default=datetime.datetime.now, editable=False)
	balanced_days = models.FloatField(default=0, help_text='Days of annual leave with no paid that have been archived by administrative stuff.')

	def __unicode__(self):
		return self.display_name
		
	class Meta:
		app_label = 'maitenance'
		verbose_name = 'Employee'
		verbose_name_plural = 'Employees'
	
	@property
	def is_admin(self):
		return self.is_administrative_staff 
	
	def is_approver_of(self, leaverequest):
		if self.domain_id.lower() in leaverequest.employee.approvers.lower():
			return True
		else:
			return False
	
	def is_approver(self):
		res = Employee.objects.filter(approvers__icontains = self.domain_id.strip(';')+';')
		return len(res) > 0
		
	def is_mine(self, leaverequest):
		if self.sid == leaverequest.employee.sid:
			return True
		else:
			return False
		
	def get_approvers(self):
		approvers = self.approvers.strip().strip(';').replace(r'\\', r'\\\\').split(';')
		return Employee.objects.filter(domain_id__in=approvers)
	
	def approvers_email(self):
		return [a.email for a in self.get_approvers()]
	
	def cc_to_email(self):
		cc = self.cc_to.strip().strip(';').replace(r'\\', r'\\\\').split(';')
		cc_to = Employee.objects.filter(domain_id__in=cc)
		emails = [c.email for c in cc_to]
		return emails
	
	def days_available(self):
		from leave.models import LeaveType
		leavetypes = LeaveType.objects.all()
		
		available_days = {}
		for leavetype in leavetypes:
			used_days, need_approval = self.get_used_leave_days(leavetype)
			leave_adjustment_days = self.get_leave_adjustment_days(leavetype.name)
			
			if leavetype.name == 'Annual Leave':
				usable_annual_leave_days = self.get_annual_leave_days()
				from decimal import Decimal
				
				total_annual_leave_days = usable_annual_leave_days + \
												self.balanced_forward + \
												self.balanced_days + \
												leave_adjustment_days
				
				ad = total_annual_leave_days - used_days - need_approval

				available_days[leavetype.name.lower().replace(' ', '_')] = {
					'total_days': total_annual_leave_days,
					'used_days': used_days,
					'need_approval': need_approval,
					'available_days': ad if ad > 0 else 0
				}
			elif leavetype.name == 'Sick Leave':
				usable_sick_leave_days = self.get_sick_leave_days() + leave_adjustment_days
				
				available_days[leavetype.name.lower().replace(' ', '_')] = {
					'total_days': usable_sick_leave_days,
					'used_days': used_days,
					'need_approval': need_approval,
					'available_days': usable_sick_leave_days - used_days - need_approval
				}
			elif leavetype.name == 'Marriage Leave':
				marriage_leave_days = leavetype.max_days
				expire_date = None
				
				mlc = self.marriageleaveconfirm_set.all()
				if mlc:
					marriage_leave_days = mlc[0].days + leave_adjustment_days
					expire_date = mlc[0].expire_date	
				
				available_days[leavetype.name.lower().replace(' ', '_')] = {
					'total_days': marriage_leave_days,
					'used_days': used_days,
					'need_approval': need_approval,
					'available_days': marriage_leave_days - used_days - need_approval,
					'expire_date': expire_date
				}
				
			else:
				tol_days = leavetype.max_days + leave_adjustment_days
				available_days[leavetype.name.lower().replace(' ', '_')] = {
					'total_days': tol_days,
					'used_days': used_days,
					'need_approval': need_approval,
					'available_days': tol_days - used_days - need_approval
				}
				
		return available_days
	
	def get_sick_leave_days(self):
		days_to = self._total_days_to_next_settlement()
		return days_to/365*self.sl_entitlement

	def _total_days_to_next_settlement(self):
		import datetime, settings
		today = datetime.date.today()
		
		# account_day = datetime.date(today.year, today.month, settings.LEAVE_REPORT_FIRST_DAY)
		# if today > account_day:
			# account_day = datetime.date(today.year, today.month+1, settings.LEAVE_REPORT_FIRST_DAY)
		
		try:
			sfd = self.start_fiscal_date.date()
		except:
			sfd = self.start_fiscal_date
		
		first_day_of_this_year = datetime.date(today.year, 1, 1)
		if sfd < first_day_of_this_year:
			sfd = first_day_of_this_year
			
		days_to = float((today - sfd).days) + 1
		return days_to
	
	def get_annual_leave_days(self):
		days_to_now = self._total_days_to_next_settlement()
		return days_to_now/365*self.al_entitlement
		
	def get_used_leave_days(self, leavetype):		
		from leave.models import LeaveRequest
		from django.db.models import Q
		lrs = LeaveRequest.objects.filter(
			(Q(period__start__year = datetime.datetime.now().year) | \
			Q(period__end__year = datetime.datetime.now().year))&
			Q(employee__id = self.id)&
			Q(leave_type__id = leavetype.id)
		).distinct()

		used_days = need_approval = 0.0
		for l in lrs:
			if l.status in (processe.status.PENDINGADMIN, processe.status.ARCHIVED):
				used_days += l.days
			elif l.status in (processe.status.PENDINGMANAGER, processe.status.WAITINGADMINCONFIRM):
				need_approval += l.days
		return used_days, need_approval
	
	def get_leave_adjustment_days(self, leavetype):
		return sum([a.adjustment_days for a in self.adjustmentdays_set.all() if a.leave_type.name == leavetype])
	
	def send_approve_alert_email(self, lr):
		template = 'maitenance/email/alert_email.txt'
		subject = "Please handle my leave request"
		receiver = lr.employee.email
		
		import settings
		host = settings.LEAVESYSTEMHOST or ''
		
		from common.utils import send_mail
		send_mail(template = template,
				sender = self.email,
				receivers = [receiver],
				context = {'host': host, 'leave_request': lr, 'receiver': lr.employee.display_name, 'sender': self.display_name},
				subject = subject,
				cc = [])

CURRENT_YEAR = str(datetime.datetime.now().year)
MONTH_CHOICES = (
	(CURRENT_YEAR+'-1',  'Jan, '+CURRENT_YEAR),
	(CURRENT_YEAR+'-2',  'Feb, '+CURRENT_YEAR),
	(CURRENT_YEAR+'-3',  'Mar, '+CURRENT_YEAR),
	(CURRENT_YEAR+'-4',  'Apr, '+CURRENT_YEAR),
	(CURRENT_YEAR+'-5',  'May, '+CURRENT_YEAR),
	(CURRENT_YEAR+'-6',  'Jun, '+CURRENT_YEAR),
	(CURRENT_YEAR+'-7',  'Jul, '+CURRENT_YEAR),
	(CURRENT_YEAR+'-8',  'Aug, '+CURRENT_YEAR),
	(CURRENT_YEAR+'-9',  'Sep, '+CURRENT_YEAR),
	(CURRENT_YEAR+'-10', 'Oct, '+CURRENT_YEAR),
	(CURRENT_YEAR+'-11', 'Nov, '+CURRENT_YEAR),
	(CURRENT_YEAR+'-12', 'Dec, '+CURRENT_YEAR)
)
try:
	from leave.models import LeaveType
except:
	LeaveType = 'LeaveType'
	
class AdjustmentDays(models.Model):
	employee = models.ForeignKey(Employee)
	leave_type = models.ForeignKey(LeaveType, blank=True, null=True)
	month = models.CharField(max_length=10, choices=MONTH_CHOICES)
	adjustment_days = models.FloatField('Deduction')
	expire_date = models.DateField(blank=True, null=True)
	comment = models.CharField(max_length = 500, blank=True)
	create_date = models.DateTimeField(auto_now_add=True)
	
	def __unicode__(self):
		return '%s adjustment' % self.month
	
	class Meta:
		app_label = 'maitenance'
		verbose_name = 'Adjustment Day'

questzhuhai/leave/forms.py
from django.forms import ModelForm, Textarea
from django import forms
from models import *

class CreateLeaveRequestForm(ModelForm):
	widget=forms.Textarea
	class Meta:
		model = LeaveRequest
		fields = ('employee','leave_type', 'status', 'days', 'comments')
		widgets = {
			'comments': Textarea(attrs={'cols': 80, 'rows': 5}),
		}

	

questzhuhai/templates/leave/change_list.html
{% extends "base.html" %}
{% load adminmedia admin_list i18n %}
{% load url from future %}
{% block title %}Leave Request Manage{% endblock %}

{% block head %}
	<link type="text/css" rel="stylesheet" href="/static/admin/css/changelists.css" />
	
	<script type="text/javascript" src="/static/scripts/core.js"></script>
	<script type="text/javascript" src="/static/scripts/RelatedObjectLookups.js"></script>
	<script type="text/javascript" src="/static/scripts/jquery.init.js"></script>
	<script type="text/javascript" src="/static/scripts/actions.min.js"></script>
	<script type="text/javascript">
	(function($) {
	$(document).ready(function($) {
	$("tr input.action-select").actions();
	});
	})(django.jQuery);
	</script> 
{% endblock %}

{% block content %}
	<div class="change-list">
  <div id="content-main">
	<h1>Select a leave request to change</h1>
    {% if messages %}
		<ul class="messagelist">
			{% for message in messages %}
			<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
			{% endfor %}
		</ul>
	{% endif %}
	{% if cl.formset.errors %}
        <p class="errornote">
        {% blocktrans count cl.formset.errors|length as counter %}Please correct the error below.{% plural %}Please correct the errors below.{% endblocktrans %}
        </p>
        {{ cl.formset.non_form_errors }}
    {% endif %}
    <div class="module{% if cl.has_filters %} filtered{% endif %}" id="changelist">
      {% block search %}{% search_form cl %}{% endblock %}
      {% block date_hierarchy %}{% date_hierarchy cl %}{% endblock %}

      {% block filters %}
        {% if cl.has_filters %}
          <div id="changelist-filter">
            <h2>{% trans 'Filter' %}</h2>
            {% for spec in cl.filter_specs %}{% admin_list_filter cl spec %}{% endfor %}
          </div>
        {% endif %}
      {% endblock %}

      <form id="changelist-form" action="" method="post"{% if cl.formset.is_multipart %} enctype="multipart/form-data"{% endif %}>{% csrf_token %}
      {% if cl.formset %}
        <div>{{ cl.formset.management_form }}</div>
      {% endif %}

      {% block result_list %}
          {% if action_form and actions_on_top and cl.full_result_count %}{% admin_actions %}{% endif %}
          {% result_list cl %}
          {% if action_form and actions_on_bottom and cl.full_result_count %}{% admin_actions %}{% endif %}
      {% endblock %}
      {% block pagination %}{% pagination cl %}{% endblock %}
      </form>
    </div>
  </div>
	</div>
{% endblock %}

questzhuhai/templates/leave/new_leave_request.html
{% extends "base.html" %}
{% load leave_utils %}
{% load compress %}
{% block title %}{% if edit %}Edit{% else %}Ask{% endif %} a leave{% endblock %}
{% block head %}
	<link rel="stylesheet" type="text/css" href="/static/admin/css/widgets.css" /> 
	<script type="text/javascript" src="/eleave/admin/jsi18n/"></script> 
	{% compress js %}
	<script type="text/javascript" src="/static/admin/js/core.js"></script>
	<script type="text/javascript" src="/static/admin/js/jquery.min.js"></script> 
	<script type="text/javascript" src="/static/admin/js/jquery.init.js"></script> 
	<script type="text/javascript" src="/static/admin/js/calendar.js"></script> 
	<script type="text/javascript" src="/static/admin/js/admin/DateTimeShortcuts-copy.js"></script>
	<script type="text/javascript" src="/static/scripts/leaverequest.js"></script>
	{% endcompress %}
	<style type="text/css">
		textarea#id_comments{width: 100%;}
		table#formtable{border-top: 5px solid #ddd;}
		
		#hor-minimalist-b {
			font-family: "Lucida Sans Unicode", "Lucida Grande", Sans-Serif;
			font-size: 12px;
			background: white;
			width: 100%;
			border-collapse: collapse;
			text-align: left;
			margin-top: 10px;
		}
		#hor-minimalist-b th {
			font-size: 14px;
			font-weight: normal;
			color: #039;
			border-bottom: 2px solid #6678B1;
			padding: 10px 8px;
		}
		
		#hor-minimalist-b td {
			border-bottom: 1px solid #CCC;
			color: #669;
			padding: 6px 8px;
		}
	</style>
{% endblock %}
{% block content %}
	<div class="leave-form">
		<div class="center"><h1>Leave Request</h1></div>
		<form id="leaveForm" method='POST' action=''>{% csrf_token %}
			<table id="formtable" style="margin: 0 auto; width: 820px;">
				<tr>
					<td class="col1"><strong>Employee:</strong></td>
					<td>{% if edit %}{{leaverequest.employee.display_name}}{% else %}{{employee.display_name}}{% endif %}</td>
				</tr>
				<tr>
					<td class="col1"><strong>Department:</strong></td>
					<td>{% if edit %}{{leaverequest.employee.department}}{% else %}{{employee.department}}{% endif %}</td>
				</tr>
				<tr>
					<td class="col1"><strong>Team:</strong></td>
					<td>{% if edit %}{{leaverequest.employee.team}}{% else %}{{employee.team}}{% endif %}</td>
				</tr>
				<tr>
					<td class="col1"><strong>Leave type:</strong></td>
					<td>
						<div>
							{{form.leave_type}}
							{% if form.leave_type.errors %}
								{{form.leave_type.errors}}
							{% endif %}
							<script>
								var login = '{{employee.display_name}}';
								var request_owner = '{% if edit %}{{leaverequest.employee.display_name}}{% else %}{{employee.display_name}}{% endif %}';
								if (login != request_owner)
								{
									$('#id_leave_type').attr('disabled', 'disabled');
								}
							</script>
							<span id="leave_type_error" class="red bold" style="margin-left: 20px;"></span>
						</div>
						<div id="leave_type_helps" style="width: 100%; display:none">
						{% for k, v in availableDays.items %}							
							<div id="{{k}}_help" class="leave_type_help">
							{% if k == "annual_leave" %}							
							<table id="hor-minimalist-b" width="100%">
								<thead>
								<tr>
									<th>Total entitled</th>
									<th>Total used</th>
									<th>Available</th>
									<th>Processing</th>
								</tr>
								</thead>
								<tbody>
								<tr>
									<td><span id="{{k}}_total_days">{{v.total_days|floatformat:2}}</span> day(s)</td>
									<td><span id="{{k}}_used_days" class="">{{v.used_days|floatformat:2}}</span> day(s)</td>
									<td><span id="{{k}}_available_days" class="">{{v.available_days|floatformat:2}}</span> day(s)</td>
									<td><span id="{{k}}_need_approval" class="">{{v.need_approval}}</span> day(s)</td>
								</tr>
								</tbody>
							</table>
							{% else %}
							<table id="hor-minimalist-b" width="100%">
								<thead>
								<tr>
									<th>Total entitled</th>
									<th>Total used</th>
									<th>Available</th>
									<th>Processing</th>
								</tr>
								</thead>
								<tbody>
								<tr>
									<td><span id="{{k}}_total_days">{{v.total_days|floatformat:2}}</span> day(s)</td>
									<td><span id="{{k}}_used_days" class="">{{v.used_days|floatformat:2}}</span> day(s)</td>
									<td><span id="{{k}}_available_days" class="">{{v.available_days|floatformat:2}}</span> day(s)</td>
									<td><span id="{{k}}_need_approval" class="">{{v.need_approval}}</span> day(s)</td>
								</tr>
								</tbody>
							</table>
							{% endif %}
							{% if v.expire_date %}
							<strong id="marriage_leave_expire_date">Expire on: {{v.expire_date|date:"Y-m-d"}}</strong>
							{% endif %} 
							</div>
						{% endfor %}
						</div>
					</td>
				</tr>
				<tr>
					<td class="col1"><strong>Period:</strong>
						<p class="tip">Please skip weekend days and public holidays!</p>
					</td>
					<td>
						{% if periods %}
							{% for p in periods %}
								<div class="period">
								From:<input id="id-start-date" value="{{p.start|date:"Y-m-d"}}" class="vDateField notdatewidget" type="text" name="start_date0" size="11" />
								<select name="start_time0" id="id_start_time" class="timeOptions">
									<option value="9" {% period_AM_selected p.start %}>AM</option>
									<option value="13" {% period_PM_selected p.start %}>PM</option>
								</select>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
								To:<input id="id-end-date" value="{{p.end|date:"Y-m-d"}}" class="vDateField notdatewidget" type="text" name="end_date0" size="11" />
								<select name="end_time0" id="id_end_time" class="timeOptions">
									<option value="9" {% period_AM_selected p.end %}>AM</option>
									<option value="13" {% period_PM_selected p.end %}>PM</option>
								</select>
								<input class="btn-delete-period" type="image" src="/static/admin/img/admin/icon_deletelink.gif" alt="" />
								</div>
							{% endfor %}
						{% else %}
							<div class="period">
							From:<input id="id-start-date" class="vDateField notdatewidget" type="text" name="start_date0" size="11" />
							<select name="start_time0" id="id_start_time" class="timeOptions">
								<option value="9" selected="selected">AM</option>
								<option value="13">PM</option>
							</select>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
							To:<input id="id-end-date" class="vDateField notdatewidget" type="text" name="end_date0" size="11" />
							<select name="end_time0" id="id_end_time" class="timeOptions">
								<option value="9">AM</option>
								<option value="13" selected="selected">PM</option>
							</select>
							</div>
						{% endif %}
						<div id="total-days" style="float:right;font-size:24px;">
							<span id="days">0</span>Day
						</div>
						<div id="add-period-box">
							<a id="link-add-period" class="add-another" href="">
								   <img src="/static/admin/img/admin/icon_addlink.gif" alt="">
								   Add another period
							<a/>
							<span id="period_warn" class='red bold' style="margin-left: 20px;"></span>							
						</div>
						<ul class="errorlist" style="display:none"><li id="period_errors"></li></ul>
						<script type="text/javascript">
							DateTimeShortcuts.showDays();
						</script>
					</td>
				</tr>
				<tr>
					<td class="col1"><strong>Status:</strong></td>
					<td>
						{{form.status}}
					</td>
				</tr>
				<tr>
					<td class="col1"><strong>Approvers:</strong></td>
					<td>
					{% if edit %}
					{{ leaverequest.employee.get_approvers|join:", " }}
					{% else %}
					{{ employee.get_approvers|join:", " }}
					{% endif %}
					</td>
				</tr>
				<tr>
					<td class="col1"><strong>Comments:</strong></td>
					<td>
						{{form.comments}}
					</td>
				</tr>
				<tr>
					<td class="col-btn" colspan="2">
						{% if edit %}
						<input type="hidden" value="1" name="modify" />
						<input type="hidden" value="{{leaverequest.days}}" name="modify_days" />
						<input type="hidden" value="{{leaverequest.id}}" name="leave_request_id" />
						{% endif %}
						<input type="hidden" value="{% if edit %}{{leaverequest.employee.id}}{% else %}{{employee.id}}{% endif %}" name="employee" />
						<img class="waiting_icon" src="/static/images/waiting.gif" alt="Waiting...">
						<input id="leave-request-submit" class="default" type="submit" value="Submit" />
					</td>
				</tr>
			</table>
		</form>
	</div>
	<script type="text/javascript">
		$(function(){
			
		});
	</script>
{% endblock %}