questzhuhai/maitenance/urls.py
from django.conf.urls.defaults import patterns, include, url
from maitenance.admin import *
from maitenance.models import *
from django.contrib.admin.sites import AdminSite
from views import admin_require

employee_admin = EmployeeAdmin(Employee, AdminSite())
dep_admin = DepartmentAdmin(Department, AdminSite())
team_admin = TeamAdmin(Team, AdminSite())

urlpatterns = patterns('',
    url(r'^reports/$', "maitenance.views.reports"),
    url(r'^settings/$', "maitenance.views.maitenance"),
    url(r'^setcycle$', "maitenance.views.setcycle"),
    url(r'^admin/add$', "maitenance.views.add_admin"),
    url(r'^admin/delete$', "maitenance.views.delete_admin"),
    url(r'^leavetype/add$', "maitenance.views.add_leave_type"),
    url(r'^leavetype/delete$', "maitenance.views.delete_leave_type"),
    url(r'^leavetype/set_notify_admin$', "maitenance.views.set_notify_admin"),
    url(r'^deps_teams$', "maitenance.views.add_department_view"),
    url(r'^dep/add$', "maitenance.views.add_department_view"),
    url(r'^dep/delete$', "maitenance.views.delete_department"),
    url(r'^get_teams_by_department$', "maitenance.views.get_teams_by_department"),
    url(r'^team/add$', "maitenance.views.add_team"),
    url(r'^team/delete$', "maitenance.views.delete_team"),
    url(r'^employees/$', admin_require(employee_admin.changelist_view)),
    url(r'^employees/add/$', admin_require(employee_admin.add_view)),
    url(r'^employees/(?P<object_id>\d+)/$', admin_require(employee_admin.change_view)),
    url(r'^employees/(?P<object_id>\d+)/delete/$', admin_require(employee_admin.delete_view)),

	url(r'^department/$', admin_require(dep_admin.changelist_view)),
	url(r'^department/add/$', admin_require(dep_admin.add_view)),
	url(r'^department/(?P<object_id>\d+)/$', admin_require(dep_admin.change_view)),
	url(r'^department/(?P<object_id>\d+)/delete/$', admin_require(dep_admin.delete_view)),
	
	url(r'^team/$', admin_require(team_admin.changelist_view)),
	url(r'^team/add/$', admin_require(team_admin.add_view)),
	url(r'^team/(?P<object_id>\d+)/$', admin_require(team_admin.change_view)),
	url(r'^team/(?P<object_id>\d+)/delete/$', admin_require(team_admin.delete_view)),
	
	url(r'^import_employees/$', 'maitenance.views.import_employees'),
	url(r'^action_logs/$', 'maitenance.views.action_logs'),
	
	url(r'^(\w+)/add$', 'maitenance.views.add_object'),
	#url(r'^(\w+)/delete$', 'maitenance.views.delete_object'),
	
	url(r'^reports/$', 'maitenance.views.reports'),
	url(r'^reports/generate$', 'maitenance.views.generate_report'),
	url(r'^reports/download/(?P<report_type>\w+)/(?P<start_date>\w{10})/(?P<end_date>\w{10})/$',
		'maitenance.views.download_leave_record_report', name='download_leave_record_report'),
	url(r'^reports/download/(?P<report_type>\w+)/(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/$',
		'maitenance.views.download_report', name='download_report'),
)

questzhuhai/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.views.generic.simple import direct_to_template

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    url(r'^eleave/admin/', include(admin.site.urls)),
    url(r'^eleave/main/', include('maitenance.urls')),
    url(r'^eleave/leave/', include('leave.urls')),
	url(r'^eleave/$', "leave.views.leave_request"),
	url(r'^$', "leave.views.leave_request"),
)

import settings
if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.STATIC_ROOT,
        }),
   )

questzhuhai/maitenance/forms.py
from django.forms import ModelForm
from maitenance.models import *

class AdminCreateForm(ModelForm):
	class Meta:
		model = Admin
		
class DepartmentForm(ModelForm):
	class Meta:
		model = Department
		
class TeamForm(ModelForm):
	class Meta:
		model = Team
		

questzhuhai/maitenance/views.py
from django.http import HttpResponse
from django.views.decorators.cache import never_cache
from django.shortcuts import render_to_response, redirect
from django.template.loader import get_template
from django.template import Context, RequestContext
import main_utils
import common.utils as utils
from common.logger import log
import simplejson as json
import settings

def admin_require(view_func):
	def is_admin(request, *args, **kwargs):
		if not request.employee.is_administrative_staff:
			return render_to_response('auth_error.html', RequestContext(request, {}))
		return view_func(request, *args, **kwargs)
	return is_admin

@admin_require
def reports(request):
	from datetime import date
	year = int(request.GET.get('year', date.today().year))
	
	year_reports, years = main_utils.leave_report(year)
	
	return render_to_response('maitenance/report.html', RequestContext(request, {'reports': year_reports, 'years': years, 'nav': 'reports'}))
	
@admin_require
def generate_report(request):
	from datetime import date, datetime
	today = date.today()
	start_date = end_date = None
	
	report_type = request.GET.get('type', 'leavereport')
	if report_type == 'leavereport':
		year = request.GET.get('year', today.year)
		month = request.GET.get('month', today.month)
		
		day = request.GET.get('day', settings.LEAVE_REPORT_FIRST_DAY)
		start_date = datetime(int(year), 1, 1)
		end_date = datetime(int(year), int(month), int(day))
		main_utils.generate_reports(report_type, int(year), int(month), int(day))
		
		subject = "Monthly leave report %s" % end_date.strftime('%Y-%m-%d')
		type = 'leave report'
		
	if report_type == 'leaverecord':
		start = request.GET.get('start')
		end = request.GET.get('end')
		
		start_date = datetime.strptime(start, "%Y-%m-%d")
		end_date = datetime.strptime(end + ' 17:30', "%Y-%m-%d %H:%M")
		main_utils.generate_reports(report_type, year = today.year, month = today.month, start_date = start_date, end_date = end_date)
	
		subject = "Monthly leave record report(%s~%s)" % (start_date.strftime('%Y-%m-%d'), end_date.strftime('%Y-%m-%d'))
		type = 'leave record'
		
	from common.utils import send_email_to_admin
	send_email_to_admin('report_notification.txt', subject, end_date, start_date, type)
	
	return redirect('/eleave/main/reports/')

@admin_require
def download_report(request, report_type, year, month, day):
	filename = '%s-%s-%s-%s.xls' % (report_type, year, month, day)
	if request.GET.get('export', 0): filename = 'export_' + filename
	return main_utils.download_report(filename)
	
@admin_require
def download_leave_record_report(request, report_type, start_date, end_date):
	filename = 'leaverecordreport-%s-%s.xls' % (start_date, end_date)
	if request.GET.get('export', 0): filename = 'export_' + filename
	return main_utils.download_report(filename)

@admin_require
def index(request):
	return render_to_response('maitenance/index.html', RequestContext(request,{}))

@admin_require
def maitenance(request):
	admins = main_utils.get_all_admins()
	leavetypes = main_utils.get_all_leave_types()
	departments = main_utils.get_all_departments()
	cycle = utils.read(utils.resfile(), 'Default', 'email.alert.cycle')
	return render_to_response('maitenance/maitenance.html',RequestContext(request, {
		'admins': admins, 
		'leavetypes': leavetypes,
		'departments': departments,
		'nav': 'settings',
		'cycle': cycle})
	)
	
@admin_require
def setcycle(request):
	if request.method == 'POST':
		cycle = request.POST.get('cycle')
		utils.write(utils.resfile(), 'Default', 'email.alert.cycle', cycle)
	return redirect('/eleave/main/settings')
	
@admin_require
def action_logs(request):
	actions = main_utils.get_all_maitenancelogs()
	return render_to_response('maitenance/action_logs.html',
							  RequestContext(request, {'actions': actions, 'nav': 'action_logs'}))

def add_object(request, model):
	pass

#######################Administrators Maintenance Interfaces##################	
@admin_require
@never_cache
def add_admin(request):
	domain_id = request.GET.get('name', '').lower()
	current_user = request.META['REMOTE_USER']
	res = main_utils.add_admin(domain_id, current_user)
	row_html = ''
	if res['data']:
		row_html = rend_row(Context({'admin': res['data']}), 'maitenance/row_admin.html')
	return HttpResponse(json.dumps({'error': res['error'], 'html': row_html, 'data': res['data'].sid if res['data'] else ''}))
	
def rend_row(data, template_name):
	template = get_template(template_name)
	return template.render(data)
	
@admin_require
@never_cache
def delete_admin(request):
	domain_id = request.GET.get('name', '').lower()
	current_user = request.META['REMOTE_USER']
	res = main_utils.delete_admin(domain_id, current_user)
	
	return HttpResponse(json.dumps({'error': res['error']}))

#######################Leave Type Maintenance Interfaces##################	

@admin_require
@never_cache
def add_leave_type(request):
	name = request.GET.get('name', '')
	current_user = request.META['REMOTE_USER']
	res = main_utils.add_leave_type(name, current_user)
	row_html = ''
	if res['data']:
		row_html = rend_row(Context({'leavetype': res['data']}), 'maitenance/row_leavetype.html')
	return HttpResponse(json.dumps({'error': res['error'], 'html': row_html, 'data': res['data'].id if res['data'] else ''}))
	
@admin_require
@never_cache
def delete_leave_type(request):
	leavetype_id = request.GET.get('id', '').lower()
	current_user = request.META['REMOTE_USER']
	res = main_utils.delete_leave_type(leavetype_id, current_user)
	
	return HttpResponse(json.dumps({'error': res['error']}))

def set_notify_admin(request):
	id = request.GET.get('id', '')
	notify_admin_str = request.GET.get('notify_admin', 'false')
	notify_admin = True if notify_admin_str == 'true' else False
	current_user = request.META['REMOTE_USER']
	
	res = main_utils.update_leave_type(id, notify_admin, current_user)
	
	return HttpResponse(json.dumps({'error': res['error']}))

@admin_require
@never_cache
def deps_and_teams(request):
	departments = main_utils.get_all_departments()
	return render_to_response('maitenance/department.html', {
		'departments': departments
	})
	
@admin_require
def add_department_view(request):
	from forms import DepartmentForm
	form = None
	if request.method == 'POST':
		form = DepartmentForm(request.POST)
		if form.is_valid():
			form.save()
	else:
		form = DepartmentForm()
		
	deps = main_utils.get_all_departments()
	
	from django.template import RequestContext

	return render_to_response('maitenance/department.html', RequestContext(request, {'form': form, 'deps': deps}))

@admin_require
@never_cache
def add_department(request):
	name = request.GET.get('name', '')
	current_user = request.META['REMOTE_USER']
	res = main_utils.add_department(name, current_user)
	row_html = ''
	if res['data']:
		row_html = rend_row(Context({'dep': res['data']}), 'maitenance/row_dep.html')
	return HttpResponse(json.dumps({'error': res['error'], 'html': row_html, 'data': res['data'].id if res['data'] else ''}))

@admin_require
@never_cache	
def delete_department(request):
	dep_id = request.GET.get('id', '')
	current_user = request.META['REMOTE_USER']
	res = main_utils.delete_department(dep_id, current_user)
	
	return HttpResponse(json.dumps({'error': res['error']}))

@admin_require
@never_cache
def add_team(request):
	dep_id = request.GET.get('dep_id', '')
	name = request.GET.get('name', '')
	current_user = request.META['REMOTE_USER']
	res = main_utils.add_team(dep_id, name, current_user)
	row_html = ''
	if res['data']:
		row_html = rend_row(Context({'team': res['data']}), 'maitenance/row_team.html')
	return HttpResponse(json.dumps({'error': res['error'], 'html': row_html, 'data': res['data'].id if res['data'] else ''}))
	
@admin_require
@never_cache	
def delete_team(request):
	id = request.GET.get('id', '')
	current_user = request.META['REMOTE_USER']
	res = main_utils.delete_team(id, current_user)
	
	return HttpResponse(json.dumps({'error': res['error']}))
	
@admin_require
def get_teams_by_department(request):
	dep_id =  request.GET.get('dep_id', '')
	res = main_utils.get_teams_by_department(int(dep_id))
	html = '<option value="" selected="selected">---------</option>'
	if res['error'] == '' and res['data']:
		for team in res['data']:
			html += '<option value="%d">%s</option>' % (team.id, team.name)
			
	return HttpResponse(json.dumps({'error': res['error'], 'html': html}))
	

from django import forms

class UploadFileForm(forms.Form):
	title = forms.CharField(max_length=150)
	file  = forms.FileField()

from django.shortcuts import redirect
@admin_require
def import_employees(request):
	error = ''
	res = {}
	current_user = request.META['REMOTE_USER']
	
	if request.method == 'POST':
		try:
			form = forms.Form(request.POST, request.FILES)
			if form.is_valid():
				file = request.FILES['file']
				main_utils.handle_uploaded_file(file)
				res = main_utils.add_employees('employees.xls', current_user)
		except BaseException,e:
			import sys
			log.Except(sys.exc_info()[1].__str__())
			error = 'Internal error while importing the employees info.'
		if error:
			res['ERROR'] = error
	return render_to_response('maitenance/employees_import_result.html', RequestContext(request, {'errors': res, 'nav': 'employees'}))

questzhuhai/templates/maitenance/action_logs.html
{% extends "base.html" %}
{% block title %}Administrator action logs{% endblock %}
{% block head %}
    <style type="text/css">
        .center-box{width:960px; margin: 0 auto;}
        .center-box h1 {margin: 10px 0;}
        .action-logs{width:100%; border-top: 1px solid #ddd;}
        .action-logs td{line-height:20px;}
        .operator{color: blue;}
    </style>
{% endblock %}

{% block content %}
    <div>
    <h1>Your recently action logs</h1>
    <table class="action-logs">
        {% for action in actions.data %}
        <tr>
            <td>
                <span class="operator">{{action.who|escape}}</span> {{action.operation}} at {{action.when}}
            </td>
        </tr>
        {% endfor %}
    </table>
    </div>
{% endblock %}

questzhuhai/templates/maitenance/archive_year_adjustment_days.html
{% extends "base.html" %}
{% load i18n l10n %}

{% block title %}Archive the adjustment days{% endblock %}
{% block head %}
    <link type="text/css" rel="stylesheet" href="/static/css/forms.css" /> 
    {% url 'admin:jsi18n' as jsi18nurl %}
    <script type="text/javascript" src="/eleave/admin/jsi18n/"></script> 
    <script type="text/javascript" src="/static/admin/js/core.js"></script> 
    <script type="text/javascript" src="/static/admin/js/jquery.init.js"></script> 
    <script type="text/javascript" src="/static/admin/js/calendar.js"></script> 
    <script type="text/javascript" src="/static/admin/js/admin/DateTimeShortcuts.js"></script> 
    <style type="text/css">
        lable{font-weight: bold; font-size: 14px; width: 200px; display: block;}
        
    </style>
{% endblock %}

{% block content %}

    <p>{% blocktrans %}Are you sure you want to archive the adjustment days of the selected {{ objects_name }}? {% endblocktrans %}</p>

    <form action="" method="post">{% csrf_token %}
	<span><strong>Year:</strong></span><input type="text" name="year" />
    <div>
    {% for obj in queryset %}
    <input type="hidden" name="{{ action_checkbox_name }}" value="{{ obj.pk|unlocalize }}" />
    {% endfor %}
	<input type="hidden" name="action" value="archive_year_adjustment_days" />
    <input type="hidden" name="post" value="yes" />
    <input type="submit" value="{% trans "  Archive  " %}" />
    </div>
    </form>
	<br />
	All of the following objects will be updated:
    {% for item in queryset %}
        <ul>{{ item }}</ul>
    {% endfor %}
{% endblock %}

questzhuhai/templates/maitenance/change_employee.html
{% extends "base.html" %}
{% load i18n admin_modify adminmedia %}
{% load url from future %}
{% block title %}Employee Manage{% endblock %}

{% block head %}
	<link type="text/css" rel="stylesheet" href="/static/css/changelists.css" />
{% endblock %}

{% block content %}
<div id="content-main">
{% block object-tools %}
{% if change %}{% if not is_popup %}
  <ul class="object-tools">
    {% block object-tools-items %}
    <li><a href="history/" class="historylink">{% trans "History" %}</a></li>
    {% if has_absolute_url %}<li><a href="../../../r/{{ content_type_id }}/{{ object_id }}/" class="viewsitelink">{% trans "View on site" %}</a></li>{% endif%}
    {% endblock %}
  </ul>
{% endif %}{% endif %}
{% endblock %}
<form {% if has_file_field %}enctype="multipart/form-data" {% endif %}action="{{ form_url }}" method="post" id="{{ opts.module_name }}_form">{% csrf_token %}{% block form_top %}{% endblock %}
<div>
{% if is_popup %}<input type="hidden" name="_popup" value="1" />{% endif %}
{% if save_on_top %}{% submit_row %}{% endif %}
{% if errors %}
    <p class="errornote">
    {% blocktrans count errors|length as counter %}Please correct the error below.{% plural %}Please correct the errors below.{% endblocktrans %}
    </p>
    {{ adminform.form.non_field_errors }}
{% endif %}

{% for fieldset in adminform %}
  {% include "admin/includes/fieldset.html" %}
{% endfor %}

{% block after_field_sets %}{% endblock %}

{% for inline_admin_formset in inline_admin_formsets %}
    {% include inline_admin_formset.opts.template %}
{% endfor %}

{% block after_related_objects %}{% endblock %}

{% submit_row %}

{% if adminform and add %}
   <script type="text/javascript">document.getElementById("{{ adminform.first_field.id_for_label }}").focus();</script>
{% endif %}

{# JavaScript for prepopulated fields #}
{% prepopulated_fields_js %}

</div>
</form></div>
{% endblock %}

questzhuhai/templates/maitenance/delete_confirmation.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}Delete Employee{% endblock %}

{% block head %}

{% endblock %}

{% block content %}
{% if perms_lacking or protected %}
    {% if perms_lacking %}
        <p>{% blocktrans with object as escaped_object %}Deleting the {{ object_name }} '{{ escaped_object }}' would result in deleting related objects, but your account doesn't have permission to delete the following types of objects:{% endblocktrans %}</p>
        <ul>
        {% for obj in perms_lacking %}
            <li>{{ obj }}</li>
        {% endfor %}
        </ul>
    {% endif %}
    {% if protected %}
        <p>{% blocktrans with object as escaped_object %}Deleting the {{ object_name }} '{{ escaped_object }}' would require deleting the following protected related objects:{% endblocktrans %}</p>
        <ul>
        {% for obj in protected %}
            <li>{{ obj }}</li>
        {% endfor %}
        </ul>
    {% endif %}
{% else %}
    <p>{% blocktrans with object as escaped_object %}Are you sure you want to delete the {{ object_name }} "{{ escaped_object }}"? All of the following related items will be deleted:{% endblocktrans %}</p>
    <ul>{{ deleted_objects|unordered_list }}</ul>
    <form action="" method="post">{% csrf_token %}
    <div>
    <input type="hidden" name="post" value="yes" />
    <input type="submit" value="{% trans "Yes, I'm sure" %}" />
    </div>
    </form>
{% endif %}
{% endblock %}

questzhuhai/templates/maitenance/delete_selected_confirmation.html
{% extends "base.html" %}
{% load i18n l10n %}

{% block title %}Delete Employee{% endblock %}

{% block content %}
{% if perms_lacking or protected %}
    {% if perms_lacking %}
        <p>{% blocktrans %}Deleting the selected {{ objects_name }} would result in deleting related objects, but your account doesn't have permission to delete the following types of objects:{% endblocktrans %}</p>
        <ul>
        {% for obj in perms_lacking %}
            <li>{{ obj }}</li>
        {% endfor %}
        </ul>
    {% endif %}
    {% if protected %}
        <p>{% blocktrans %}Deleting the selected {{ objects_name }} would require deleting the following protected related objects:{% endblocktrans %}</p>
        <ul>
        {% for obj in protected %}
            <li>{{ obj }}</li>
        {% endfor %}
        </ul>
    {% endif %}
{% else %}
    <p>{% blocktrans %}Are you sure you want to delete the selected {{ objects_name }}? All of the following objects and their related items will be deleted:{% endblocktrans %}</p>
    {% for deletable_object in deletable_objects %}
        <ul>{{ deletable_object|unordered_list }}</ul>
    {% endfor %}
    <form action="" method="post">{% csrf_token %}
    <div>
    {% for obj in queryset %}
    <input type="hidden" name="{{ action_checkbox_name }}" value="{{ obj.pk|unlocalize }}" />
    {% endfor %}
    <input type="hidden" name="action" value="delete_selected" />
    <input type="hidden" name="post" value="yes" />
    <input type="submit" value="{% trans "Yes, I'm sure" %}" />
    </div>
    </form>
{% endif %}
{% endblock %}

questzhuhai/templates/maitenance/employee_list.html
{% extends "base.html" %}
{% load adminmedia admin_list i18n %}
{% load url from future %}
{% block title %}Employee Manage{% endblock %}

{% block head %}
	<link type="text/css" rel="stylesheet" href="/static/css/changelists.css" />
	
	<script type="text/javascript" src="/static/scripts/core.js"></script>
	<script type="text/javascript" src="/static/scripts/RelatedObjectLookups.js"></script>
	<script type="text/javascript" src="/static/scripts/jquery.init.js"></script>
	<script type="text/javascript" src="/static/scripts/actions.min.js"></script>
	<script type="text/javascript">
	(function($) {
		$(document).ready(function($) {
			var filters = [];
			get_filters();
			$("tr input.action-select").actions();
			
			// Add anchor tag for Show/Hide link
			var elem = $("div#changelist-filter");
			//$(elem).find("h2").first().append(' (<a id="fieldsetcollapser" class="collapse-toggle" href="#">Show</a>)');
			$("div#changelist-filter .filter-item").hide();

			// Add toggle to anchor tag
			$("div#changelist-filter h2").toggle(
				function() { // Show
					$('a.collapse-toggle').text("Hide");
					$("div#changelist-filter .filter-item").show();
					return false;
				},
				function() { // Hide
					$('a.collapse-toggle').text("Show");
					$("div#changelist-filter .filter-item").hide();
					return false;
				}
			);

			function get_filters(){
				$("div.filter-item ul li.selected").each(function(){
					var f = $.trim($(this).text());
					if (f != 'All' && f != 'Any date'){	
						filters.push(f); 
					}
				});
				$('#filter_text').text(filters.join(' + '));
			}
		});
	})(django.jQuery);
	
	</script> 
	
	
{% endblock %}

{% block content %}
	<div class="change-list">
  <div id="content-main">
    <h1>Select an employee to change</h1>
	{% if messages %}
		<ul class="messagelist">
			{% for message in messages %}
			<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
			{% endfor %}
		</ul>
	{% endif %}
	{% block object-tools %}
      {% if has_add_permission %}
        <ul class="object-tools">
          {% block object-tools-items %}
            <li>
              <a href="add/" class="addlink">
                {% blocktrans with cl.opts.verbose_name as name %}Add {{ name }}{% endblocktrans %}
              </a>
            </li>
          {% endblock %}
        </ul>
      {% endif %}
    {% endblock %}
    {% if cl.formset.errors %}
        <p class="errornote">
        {% blocktrans count cl.formset.errors|length as counter %}Please correct the error below.{% plural %}Please correct the errors below.{% endblocktrans %}
        </p>
        {{ cl.formset.non_form_errors }}
    {% endif %}
    <div class="module{% if cl.has_filters %} filtered{% endif %}" id="changelist">
      {% block search %}{% search_form cl %}{% endblock %}
      {% block date_hierarchy %}{% date_hierarchy cl %}{% endblock %}

      {% block filters %}
        {% if cl.has_filters %}
          <div id="changelist-filter">
            
			<h2 id="emp_filter" title="Click to toggle filter block.">{% trans 'Filter' %}
			(<a id="fieldsetcollapser" class="collapse-toggle" href="#">Show</a>)
			<span id="filter_text"></span>
			</h2>
            {% for spec in cl.filter_specs %}<div class="filter-item">{% admin_list_filter cl spec %}</div>{% endfor %}
			
          </div>
        {% endif %}
      {% endblock %}

      <form id="changelist-form" action="" method="post"{% if cl.formset.is_multipart %} enctype="multipart/form-data"{% endif %}>{% csrf_token %}
      {% if cl.formset %}
        <div>{{ cl.formset.management_form }}</div>
      {% endif %}

      {% block result_list %}
          {% if action_form and actions_on_top and cl.full_result_count %}{% admin_actions %}{% endif %}
          {% result_list cl %}
          {% if action_form and actions_on_bottom and cl.full_result_count %}{% admin_actions %}{% endif %}
      {% endblock %}
      {% block pagination %}{% pagination cl %}{% endblock %}
      </form>
    </div>
  </div>
	</div>
	<div id="import_emp">
		<form id="import_form" action="/eleave/main/import_employees/" method="POST" enctype="multipart/form-data">{% csrf_token %}
			<h3 style="display: inline;">Import employees data from excell file:</h3>
			<input id="id_file" type="file" name="file" />
			<input id="id_import_btn" type="submit" value="import" />
			&nbsp;&nbsp;&nbsp;&nbsp;
			<span id="id_import_error" class="invisible red"></span>
		</form>
	</div>
	<script type="text/javascript">
		(function($) {
			$(document).ready(function($) {
				$('#id_import_btn').click(function(e){
					e.preventDefault();
					var filename = $('#id_file').val();
					if (filename == '')
					{
						$("#id_import_error").text('File can not be empty!').show();
					}
					else
					{
						$("#id_import_error").text('').hide();
						$('#import_form').submit();
					}
				});
			});
		})(django.jQuery);
	</script>
{% endblock %}

questzhuhai/templates/maitenance/generate_report_successful.html
{% extends "base.html" %}
{% load i18n l10n %}

{% block title %}Generate leave report{% endblock %}
{% block head %}
    <link type="text/css" rel="stylesheet" href="/static/css/forms.css" /> 
    {% url 'admin:jsi18n' as jsi18nurl %}
    <script type="text/javascript" src="/eleave/admin/jsi18n/"></script> 
    <script type="text/javascript" src="/static/admin/js/core.js"></script> 
    <script type="text/javascript" src="/static/admin/js/jquery.init.js"></script> 
    <script type="text/javascript" src="/static/admin/js/calendar.js"></script> 
    <script type="text/javascript" src="/static/admin/js/admin/DateTimeShortcuts.js"></script> 
    <style type="text/css">
        lable{font-weight: bold; font-size: 14px; width: 200px; display: block;}
        
    </style>
{% endblock %}

{% block content %}

    <p>Generate report file successfully!
	<a href="{{link}}">Click here to download the report file.</a>
	</p>
{% endblock %}

questzhuhai/templates/maitenance/row_admin.html
<tr id="{{admin.sid}}" class="admin-row">
	<td id="admin-name"><span>{{admin.domain_id}}</span></td>
	<td id="admin-delete-btn">
		<input name="{{admin.domain_id|escapejs}}" type="hidden" />
		<input id="btn-delete-admin-{{admin.sid}}" name="{{admin.domain_id}}" src="/static/images/delete_user_22.png" type="image" align="right" />
	</td>
</tr>

questzhuhai/templates/maitenance/row_dep.html
<li>
	<input id="btn-delete-dep-{{dep.id}}" name="{{dep.id}}" src="/static/images/delete.gif" type="image" align="left" />&nbsp;
	<a href="#vtabs-content-a">{{dep.name}}</a>
</li>

questzhuhai/templates/maitenance/row_team.html
<div id="t-item">
	<a href="vtabs-content-a">{{team.name}}</a>
	<input id="btn-delete-team-{{team.id}}" name="{{team.id}}" src="/static/images/delete.gif" type="image" align="right" />
</div>